import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/component/NavBar'
import Footer from '@/component/Footer/Footer'




const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'D-vol-Per',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Footer />
        
        {children}
        </body>
    </html>
  )
}





